basePath: '{{.BasePath}}'
definitions:
  student.StudentInfo:
    properties:
      Age:
        type: integer
      Gold:
        type: integer
      Name:
        type: string
      Score:
        type: integer
      Sex:
        type: integer
      UserID:
        type: integer
    type: object
host: '{{.Host}}'
info:
  contact: {}
  description: '{{.Description}}'
  license: {}
  title: '{{.Title}}'
  version: '{{.Version}}'
paths:
  /userinfo/{userid}:
    get:
      consumes:
      - application/json
      parameters:
      - description: 用户ID
        in: path
        name: userid
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "0":
          description: 用户信息
          schema:
            $ref: '#/definitions/student.StudentInfo'
            type: object
      summary: 查询用户信息
swagger: "2.0"
