// Code generated by protoc-gen-go. DO NOT EDIT.
// source: student.proto

package student

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// 用户信息
type StudentInfo struct {
	UserID               uint64   `protobuf:"varint,1,opt,name=UserID,proto3" json:"UserID,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Age                  int64    `protobuf:"varint,3,opt,name=Age,proto3" json:"Age,omitempty"`
	Sex                  int64    `protobuf:"varint,4,opt,name=Sex,proto3" json:"Sex,omitempty"`
	Gold                 uint64   `protobuf:"varint,5,opt,name=Gold,proto3" json:"Gold,omitempty"`
	Score                uint64   `protobuf:"varint,6,opt,name=Score,proto3" json:"Score,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StudentInfo) Reset()         { *m = StudentInfo{} }
func (m *StudentInfo) String() string { return proto.CompactTextString(m) }
func (*StudentInfo) ProtoMessage()    {}
func (*StudentInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_94a1c1b032ad0c00, []int{0}
}

func (m *StudentInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StudentInfo.Unmarshal(m, b)
}
func (m *StudentInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StudentInfo.Marshal(b, m, deterministic)
}
func (m *StudentInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StudentInfo.Merge(m, src)
}
func (m *StudentInfo) XXX_Size() int {
	return xxx_messageInfo_StudentInfo.Size(m)
}
func (m *StudentInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_StudentInfo.DiscardUnknown(m)
}

var xxx_messageInfo_StudentInfo proto.InternalMessageInfo

func (m *StudentInfo) GetUserID() uint64 {
	if m != nil {
		return m.UserID
	}
	return 0
}

func (m *StudentInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *StudentInfo) GetAge() int64 {
	if m != nil {
		return m.Age
	}
	return 0
}

func (m *StudentInfo) GetSex() int64 {
	if m != nil {
		return m.Sex
	}
	return 0
}

func (m *StudentInfo) GetGold() uint64 {
	if m != nil {
		return m.Gold
	}
	return 0
}

func (m *StudentInfo) GetScore() uint64 {
	if m != nil {
		return m.Score
	}
	return 0
}

func init() {
	proto.RegisterType((*StudentInfo)(nil), "student.StudentInfo")
}

func init() { proto.RegisterFile("student.proto", fileDescriptor_94a1c1b032ad0c00) }

var fileDescriptor_94a1c1b032ad0c00 = []byte{
	// 149 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2d, 0x2e, 0x29, 0x4d,
	0x49, 0xcd, 0x2b, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x87, 0x72, 0x95, 0xda, 0x19,
	0xb9, 0xb8, 0x83, 0x21, 0x6c, 0xcf, 0xbc, 0xb4, 0x7c, 0x21, 0x31, 0x2e, 0xb6, 0xd0, 0xe2, 0xd4,
	0x22, 0x4f, 0x17, 0x09, 0x46, 0x05, 0x46, 0x0d, 0x96, 0x20, 0x28, 0x4f, 0x48, 0x88, 0x8b, 0xc5,
	0x2f, 0x31, 0x37, 0x55, 0x82, 0x49, 0x81, 0x51, 0x83, 0x33, 0x08, 0xcc, 0x16, 0x12, 0xe0, 0x62,
	0x76, 0x4c, 0x4f, 0x95, 0x60, 0x56, 0x60, 0xd4, 0x60, 0x0e, 0x02, 0x31, 0x41, 0x22, 0xc1, 0xa9,
	0x15, 0x12, 0x2c, 0x10, 0x91, 0xe0, 0xd4, 0x0a, 0x90, 0x3e, 0xf7, 0xfc, 0x9c, 0x14, 0x09, 0x56,
	0xb0, 0x69, 0x60, 0xb6, 0x90, 0x08, 0x17, 0x6b, 0x70, 0x72, 0x7e, 0x51, 0xaa, 0x04, 0x1b, 0x58,
	0x10, 0xc2, 0x49, 0x62, 0x03, 0xbb, 0xcc, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0x86, 0x3b, 0x52,
	0xc4, 0xaa, 0x00, 0x00, 0x00,
}
